/*  STATUS -- Printing list of Fibonacci sequence up to 100
*/

/*  MOTIVATION

    This file provides a demonstration of the creation of arrays by functions,
    returning pointers to those arrays, and the usage of those array pointers.

 */

/*  PROBLEM

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

ANSWER: 4613732

 */

#include <stdio.h>
#include <stdlib.h>

int fibonacci(int first, int second)
/*
    Returns the next Fibonacci term, given first and second
*/
{
    int nxt;
    nxt = first + second;
    return nxt;
}

/*
  A better solution would use a Fibonacci generator that returns a pointer to an array of the terms of the sequence.  This would allow for more elegant code generating the sequence, and more elegant code checking terms for even status.

  Plan:
  - read up on creating arrays and adding terms to them
  - read up on returning and using pointers, and pointers to arrays
  - read up on iterating through arrays

  Don't guess, write intelligently

  Objective is elegant code, written elegantly



 */


int* fibonacci_ry(int first, int second, int max)
/*
    Returns a pointer to an array whose contents are the elements of the
    Fibonacci sequence less than value 'max'.

    NOTE: Currently sequence length is constrained by hard code in function.

    weed: currently, returned array has zeroes for items after the last Fibonacci sequence value.  How to revise to return array that has only the Fibonacci values, and no zeroes?

 */
{
    int ndx = 0;
    int nxt = 0;
    int SEQUENCE_LENGTH = 100;
    int* p_sq = malloc(sizeof(int) * SEQUENCE_LENGTH);

    p_sq[ndx] = first;
    ndx++;
    p_sq[ndx] = second;
    ndx++;

    //  Put terms in array
    while ( ( nxt < max ) && ( ndx <= SEQUENCE_LENGTH - 1 ) ) {
        nxt = fibonacci(first, second);
        if ( ( nxt < max ) && ( ndx <=  SEQUENCE_LENGTH - 1 ) ) {
            p_sq[ndx] = nxt;
        }
        first = second;
        second = nxt;
        ndx++;
    }

    //return *p_sq;
    return p_sq;
}  

main()
/*
    Prints Fibonacci sequence from 1 to less than 100.

    Does so from generated array of Fibonacci values.

 */
{
    int *p_ry;
    int i = 0;
    int val;

    p_ry = fibonacci_ry(1, 2, 100);

    // Both work
    while ( ( ( val = p_ry[i] ) < 100 ) && val > 0 ) {
    //-while ( ( ( val = *(p_ry + i) ) < 100 ) && val > 0 ) {
        printf("%d\n", val);
        i++;
    }
}
