/*  STATUS -- NOT WORKING
    - compiler generates warnings
    - program output is gibberish
*/

/*  MOTIVATION

    This file provides a demonstration of the creation of arrays by functions,
    returning pointers to those arrays, and the usage of those array pointers.

 */

/*  PROBLEM

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

ANSWER: 4613732

 */

#include <stdio.h>
#include <stdlib.h>

int fibonacci(int first, int second)
/*
    Returns the next Fibonacci term, given first and second
*/
{
    int nxt;
    nxt = first + second;
    return nxt;
}

/*
  A better solution would use a Fibonacci generator that returns a pointer to an array of the terms of the sequence.  This would allow for more elegant code generating the sequence, and more elegant code checking terms for even status.

  Plan:
  - read up on creating arrays and adding terms to them
  - read up on returning and using pointers, and pointers to arrays
  - read up on iterating through arrays

  Don't guess, write intelligently

  Objective is elegant code, written elegantly



 */

char (*fibonacci_ry(int first, int second, int max))[100]
//-int (*fibonacci_ry(int first, int second, int max))[100]
/*
    Returns a pointer to an array whose contents are the elements of the
    Fibonacci sequence.

    NOTE: Currently sequence length is constrained by hard code in function.

    WARNING
    Works, but gets warning:
        warning: assignment from incompatible pointer type [enabled by default]

    Answer may be in
    http://stackoverflow.com/questions/6474104/difference-between-pointer-to-pointer-and-pointer-to-array

 */
{
    /*
        Create array, pointer to array, per K&R 82
     */
    int ndx = 0;
    int nxt = 0;
    int SEQUENCE_LENGTH = 100;
    int sq[SEQUENCE_LENGTH];
    int *p_sq;

    sq[ndx] = first;
    ndx++;
    sq[ndx] = second;
    ndx++;

    //  Put terms in array
    while ( ( nxt < max ) && ( ndx <= SEQUENCE_LENGTH - 1 ) ) {
        nxt = fibonacci(first, second);
        if ( ( nxt < max ) && ( ndx <=  SEQUENCE_LENGTH - 1 ) ) {
            sq[ndx] = nxt;
        }
        first = second;
        second = nxt;
        ndx++;
    }

    p_sq = sq;
    //return *p_sq;
    return p_sq;
}  

main()
{
    int *p_ry;
    int i;

    p_ry = fibonacci_ry(1, 2, 100);

    for ( i = 0; i < 100; i++ ) {
        printf("%d\n", *(p_ry + i));
    }
}
