#include <stdio.h>

/*
    This file provides a tighter writing of a brute-force solution to the
    problem.

 */

/*

PROBLEM
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

ANSWER: 4613732

 */


main()
{
    int first = 0, second = 1, next, total = 0;
    int MAX = 4000000;

    while ( ( next = first + second ) <= MAX ) {
        if ( next % 2 == 0 ) {
            total += next;
        }
        first = second;
        second = next;
    }
    printf("%d\n", total);
}
