#include <stdio.h>

/*

PROBLEM
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

ANSWER: 4613732

 */


int fibonacci(int first, int second)
/*
    Returns the next Fibonacci term, given first and second
*/
{
    int nxt;
    nxt = first + second;
    return nxt;
}


int sum_fibonacci_even(int first, int second, int max_term)
/*
    Prints out sum of even terms of Fibonacci sequence less than max_term
 */
{
    int nxt, total=0;

    if ( first % 2 == 0 ) {
        total += first;
    }
    if ( second % 2 == 0 ) {
        total += second;
    }

    while ( ( nxt = fibonacci(first, second) ) < max_term ) {
        /* Check for even */
        if ( nxt % 2 == 0 ) {
            total += nxt;
        }
        first = second;
        second = nxt;
    }  

    return total;
}  

main()
{
    int val;
    val = sum_fibonacci_even(1, 2, 4000000);
    printf("%d\n", val);
}
