#include <stdio.h>

/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

ANSWER: 4613732

 */


int fibonacci(int first, int second)
/*
    Returns the next Fibonacci term, given first and second
*/
{
    int nxt;
    nxt = first + second;
    return nxt;
}

void fibonacci_sequence(int first, int second, int max)
/*
    Prints out terms of Fibonacci sequence, stopping when term exceeds max value
 */
{
    int nxt;

    printf("%d\n", first);
    printf("%d\n", second);

    while ( ( nxt = fibonacci(first, second) ) < max ) {
        printf("%d\n", nxt);
        first = second;
        second = nxt;
    }  
}  

void fibonacci_even(int first, int second, int max)
/*
    Prints out even terms of Fibonacci sequence, stopping when term exceeds max value
 */
{
    int nxt;

    if ( first % 2 == 0 ) {
        printf("%d\n", first);
    }
    if ( second % 2 == 0 ) {
        printf("%d\n", second);
    }

    while ( ( nxt = fibonacci(first, second) ) < max ) {
        /* Check for even */
        if ( nxt % 2 == 0 ) {
            printf("%d\n", nxt);
        }
        first = second;
        second = nxt;
    }  
}  

int sum_fibonacci_even(int first, int second, int max)
/*
    Sums the even terms of a Fibonacci sequence, terminating when term exceeds max value
 */
{
    int nxt, total=0;

    if ( first % 2 == 0 ) {
        printf("%d\n", first);
        total += first;
    }
    if ( second % 2 == 0 ) {
        printf("%d\n", second);
        total += second;
    }

    while ( ( nxt = fibonacci(first, second) ) < max ) {
        /* Check for even */
        if ( nxt % 2 == 0 ) {
            printf("%d\n", nxt);
            total += nxt;
        }
        first = second;
        second = nxt;
    }  

    return total;
}  

/*
main()
{
    // fibonacci_sequence(1, 2, 100);
    int val;
    val = sum_fibonacci_even(1, 2, 4000000);
    printf("%d\n", val);
}
 */

/*
  A better solution would use a Fibonacci generator that returns a pointer to an array of the terms of the sequence.  This would allow for more elegant code generating the sequence, and more elegant code checking terms for even status.

  Plan:
  - read up on creating arrays and adding terms to them
  - read up on returning and using pointers, and pointers to arrays
  - read up on iterating through arrays

  Don't guess, write intelligently

  Objective is elegant code, written elegantly



 */

void fibonacci_ry(int first, int second, int max)
/*
    Returns an array whose contents are the elements of the Fibonacci sequence.

    NOTE: Currently sequence length is constrained by hard code in function.

 */
{
    /*
        Create array, pointer to array, per K&R 82
     */
    int ndx = 0;
    int nxt;
    int SEQUENCE_LENGTH = 10;
    int sq[SEQUENCE_LENGTH];
    int *p_sq;
    p_sq = &sq[0];

    sq[ndx] = first;
    ndx++;
    sq[ndx] = second;

    //  Put terms in array
    while ( nxt < max || ndx < SEQUENCE_LENGTH ) {
        nxt = fibonacci(first, second);
        if ( nxt < max || ndx < SEQUENCE_LENGTH ) {
            sq[ndx] = nxt;
        }
        second = nxt;
        first = second;
        ndx++;
    }

    return p_sq;

}  

// how to loop the array to print out contents?
