#include <stdio.h>

/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

ANSWER: 4613732

 */


int fibonacci(int first, int second)
/*
    Returns the next Fibonacci term, given first and second
*/
{
    int nxt;
    nxt = first + second;
    return nxt;
}

void fibonacci_sequence(int first, int second, int max)
/*
    Prints out terms of Fibonacci sequence, stopping when term exceeds max value
 */
{
    int nxt;

    printf("%d\n", first);
    printf("%d\n", second);

    while ( ( nxt = fibonacci(first, second) ) < max ) {
        printf("%d\n", nxt);
        first = second;
        second = nxt;
    }  
}  

void fibonacci_even(int first, int second, int max)
/*
    Prints out even terms of Fibonacci sequence, stopping when term exceeds max value
 */
{
    int nxt;

    if ( first % 2 == 0 ) {
        printf("%d\n", first);
    }
    if ( second % 2 == 0 ) {
        printf("%d\n", second);
    }

    while ( ( nxt = fibonacci(first, second) ) < max ) {
        /* Check for even */
        if ( nxt % 2 == 0 ) {
            printf("%d\n", nxt);
        }
        first = second;
        second = nxt;
    }  
}  

int sum_fibonacci_even(int first, int second, int max)
/*
    Prints out even terms of Fibonacci sequence, stopping when term exceeds max value
 */
{
    int nxt, total=0;

    if ( first % 2 == 0 ) {
        printf("%d\n", first);
        total += first;
    }
    if ( second % 2 == 0 ) {
        printf("%d\n", second);
        total += second;
    }

    while ( ( nxt = fibonacci(first, second) ) < max ) {
        /* Check for even */
        if ( nxt % 2 == 0 ) {
            printf("%d\n", nxt);
            total += nxt;
        }
        first = second;
        second = nxt;
    }  

    return total;
}  

main()
{
    // fibonacci_sequence(1, 2, 100);
    int val;
    val = sum_fibonacci_even(1, 2, 4000000);
    printf("%d\n", val);
}
